### ISSUE TITLE
Can't save website to a group using Fx menu anymore

### ISSUE THREAD

**Issue by Scribe-uk** [fastaddons/GroupSpeedDial#65] opened 2021-08-09 09:01 UTC
Hi Juraj. Running Android 6 and 9 on tablets, with Firefox 68.11.0 on both: Since GSD 16 it hasn't been possible to save a website to a group using the Firefox 3-dot menu > Group Speed Dial > Add this page to dial. It used to give an option to select a group then edit and save, but now nothing happens at all. It's still possible to manually select an empty dial then paste in the URL but that hasn't been necessary before.

Keep up the good work!

**Comment by fastaddons** [comment] 2021-08-09 09:17
Thanks for reporting! I can confirm it's indeed broken even in the new Firefox for Android (Nightly).
I have few more small things to fix so I will be releasing update probably today or tomorrow.

Also a heads up, the old Firefox 68 for Android is not supported by Mozilla anymore (sadly) and my debugger doesn't work with it anymore as well, so I have no way to debug it. I will try to keep the support as much as possible but probably by the end of this year (after ESR 91 is released) I will drop support as well.
So what I'm trying to say is that you may want to upgrade to Firefox Nightly on your phone where all addons can be installed. Also this new Firefox even though it's not perfect (or far from perfect), it's still much faster than the old one and has security updates.

I will try to optimize my addon more for phones and maybe try to get to the "Recommended extensions program" and then being available also for release channel, not just the Nightly channel.

**Comment by Scribe-uk** [comment] 2021-08-09 09:50
No rush fixing it - just wanted you to be aware. Yes I stayed on the old version of Fx because of the lack of extension support with the new one, but I didn't know GSD would work on Nightly, so maybe I'll try that out - it looks like I'll have to in the end!

Thanks for all your work. I wish I had your talent!

**Comment by fastaddons** [comment] 2021-08-13 09:53
Fixed in 16.3, released now, I've just tested it and it works :)
I've switched to Nightly because the old 68 was no longer synchronizing with my Firefox account so I was not able to send and receive send tabs.
But the Nightly works pretty well, also addons works there fine, just the initial setup is a bit complicated. More info here:
https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/
Have a nice weekend :)

**Closed by fastaddons** 2021-08-13 09:53 UTC

**Comment by Scribe-uk** [comment] 2021-08-15 11:12
Thanks for the fix Juraj, I can confirm that it's working again now :)
