### ISSUE TITLE
"Always open in new tab" behavior changed

### ISSUE THREAD

**Issue by thevladsoft** [fastaddons/GroupSpeedDial#104] opened 2022-01-02 13:15 UTC
Starting with version 18, tabs will open always besides the Groupsppeddial tab, indifferently if "Always open in new tab" is selected. Until version 17.1, this option allowed to chose if you wanted the tab to open as a new tab (to the right of the rest of the tab), or just beside the current one. This breaks the behavior for those who have the Groupsppeddial tab pinned.

**Steps To Reproduce**
Install the any version starting from 18.0

**Expected behavior**
That option to behave as before: allow you to chose where the tab is going to open.

**Device info:**
 - operating system: Linux Debian bookworm
 - Browser and version: Firefox 95.0.2 32bits
 - GroupSpeedDial version: 18+

**Comment by fastaddons** [comment] 2022-01-02 17:07
Hello,
Could you send me steps to reproduce?
I have option to open in a new tab in many places so I'm not sure which one are you talking about.
It's strange though, I'm not sure I've changed this recently, but I will investigate and fix. Just send me more info, thanks!

**Comment by thevladsoft** [comment] 2022-01-03 00:27
This option here (sorry I can only take the screenshot in spanish)

![Screenshot_20220102_201812](https://user-images.githubusercontent.com/4398314/147893132-c495c27d-4764-4410-b471-f1f57d589aae.png)

All I can tell you is that if I downgrade to version 17.1, checking and unchecking this option changes where the new tab will appear. In version 18+ it does nothing.

**Comment by fastaddons** [comment] 2022-01-03 19:09
Thanks!
I've found the problem, I will fix this in the 18.2 version probably tomorrow.

**Comment by fastaddons** [comment] 2022-01-05 09:10
I'm sorry for the delay, I've got sick yesterday and spend whole day in bed. I'm not sure I can fix it today, so hopefully tomorrow.

**Comment by Gabby1969** [comment] 2022-01-06 12:15
I have experinced the same problem. Juraj please fix it as soon as possible, because it is very annoying.
Thanks
Gabby

**Comment by fastaddons** [comment] 2022-01-06 13:22
I'm working on it now, please be patient :), I'm still not fully recovered but I will try to release it today.

**Comment by Gabby1969** [comment] 2022-01-06 14:14
Ok I got it. I wish you get well soon.
Regards
Gabby

**Comment by fastaddons** [comment] 2022-01-06 18:35
**18.2 was just released for Firefox - but you will also need to activate this option:**
![Screenshot 2022-01-06 19 24 57](https://user-images.githubusercontent.com/55486931/148432442-9ad5d728-87ab-4819-ab22-7290b2f5a644.png)

Why?
You see, the bug you are experiencing is actually a feature. When you open a tab, it should be open with a relation to a parent (opener) tab. So that when you close the tab, then the opener tab is re-focused. And the "openerTabId" was missing so it wasn't working correctly and someone pointed it out, so I've fixed it in 18.0. 
Sadly by specifying the opener tab, Firefox will also change the position of the new tab to next to current tab or "somewhere close" if you are opening multiple tabs.

Anyway, with this new option you should be able to restore original behavior.

Chrome version will be released when Chrome store reviews it, so maybe a few hours later.

**Closed by fastaddons** 2022-01-06 18:35 UTC
Labels: bug

**Comment by thevladsoft** [comment] 2022-01-08 13:43
Thank you!.  I imagine having so many options can make it sometimes hard to please every one's tastes sometimes. So Thanks for adding this option.
