### ISSUE TITLE
Uploading custom thumbnail to public library breaks the dial

### ISSUE THREAD

**Issue by Mav3r1x** [fastaddons/GroupSpeedDial#39] opened 2021-03-09 15:56 UTC
**Describe the bug**
After creating a dial, it creates a thumbnail by visiting the page. However, I like to use a custom thumbnail whenever possible. After using a custom thumbnail (from a link), when you click Advanced>Upload thumbnail to public library option, the thumbnail reverts back to the original (previously created by addon) image.

I checked, and the new thumbnail is now available in the public library, but it is not possible to select/use it.

You have to delete your dial, recreate it, and then select the thumbnail from public library.

**Steps To Reproduce**
described above

**Expected behavior**
Thumbnail should not revert back to the previously created one.

**Device info:**
 - operating system: Windows 10 pro
 - Browser and version: Chrome v89
 - GroupSpeedDial version: 15.5

**Comment by Mav3r1x** [comment] 2021-03-23 13:03
Any update on this?

**Comment by fastaddons** [comment] 2021-03-23 13:25
Don't worry, I will look into it for the next release 15.6. Sounds easy enough.
I'm finishing Safari version now, after it's done I'm gonna work on 15.6 release (mostly bugfixing). So hopefully this week if things goes well.

**Comment by fastaddons** [comment] 2021-04-14 12:25
Hello, again.
Just a small update - things are not going well :). 
I can't believe 22 days passed so quickly!!!
But I'm getting there... hopefully this week will be new release.

**Comment by Mav3r1x** [comment] 2021-05-05 11:57
Hi.

So I have updated to 15.6, but this issue is still there.

**Comment by fastaddons** [comment] 2021-05-05 12:10
Hello,
It will be fixed in 15.7, I'm working on it now :)
I'm sorry for the delay.
I was not able to reproduce the issue before releasing the 15.6, but I can reproduce it now.
The new version should be released later today for Firefox and soon for Chrome (depending how fast they review it)

**Comment by fastaddons** [comment] 2021-05-05 14:48
OK it took me a while but I've fixed it now. It will be part of the 15.7 release. I will try to do the release today, but maybe it will be tomorrow because it's getting late and I wanted to fix two more small issues.
Thank you for your patience :) and thank you for reporting bugs!

**Closed by fastaddons** 2021-05-05 14:48 UTC
Labels: bug

**Comment by fastaddons** [comment] 2021-05-05 17:33
New version is out (for Firefox), Chrome version is being reviewed.
