### ISSUE TITLE
Update background image per browser session (until closing the browser) only, not tab refresh

### ISSUE THREAD

**Issue by simurq** [fastaddons/GroupSpeedDial#211] opened 2022-12-19 15:24 UTC
**Is your feature request related to a problem? Please describe.**
It's not a problem, just a bit of annoyance waiting for the background [image from URL](https://source.unsplash.com/random?orientation=landscape&size=1920x1080) to update. It often lags behind my typing in the address bar and fails to show up before I press Enter.

I know it's possible to use a background image stored locally once and for all and forget about it, but a new image on each browser session (not tab!) is better, of course.

**Describe the solution you'd like**
It would be better if updates occurred only once per browser session, with the background image remaining the same until the browser is closed. Similar to images from Bing, which do not update on other tabs as well. For the convenience of users who think differently, this feature might be tied to a checkbox option like "Don't update background image [ on each tab opening | until I close the browser ]", or "Update background image per browser session only", etc.

Thank you!

**Comment by fastaddons** [comment] 2022-12-29 21:54
I'm not sure I understand :).
In the browsers where I use this super old feature, it will change the background usually shortly after opening browser.
If the sudden change is disturbing, I could not-change the background in existing tabs and only new tabs would have a new background.

**Comment by simurq** [comment] 2022-12-30 08:40
It's not about "sudden change", rather a change at all. ))) As I said above, each *opening of a tab* refreshes/updates the background image. That is disturbing... Therefore, as I suggested above, it would be nice if the page refreshed per browser session only, not on each tab. Unfortunately, that's exactly what happens when I select the `Picture from URL` option. You could additionally provide a new option to turn on/off say "Update URL image per browser session only", something like this.

Thanks for understanding!

**Comment by simurq** [comment] 2022-12-30 08:54
> It's not about "sudden change", rather a change at all, or a change on each new tab. ))) As I said above, each _opening of a tab_ refreshes/updates the background image. That is disturbing. I would even say ineffective on poor Internet connections or heavy images, because a user would prefer inserting a search term into the address bar and pressing `Enter` than waiting an image load on the newly opened tab, no? )) Therefore, as I suggested above, it would be nice if the page refreshed **once per browser session only**, not on each tab. Unfortunately, that's exactly what's happening when I select the `Picture from URL` option. You could additionally provide a new option to turn on/off say "Update URL image per browser session only", or something like this.
> 
> Thanks for understanding!

**Comment by fastaddons** [comment] 2023-01-14 13:19
Hello,
I'm sorry for the huge delay!

So, the problem is not what I thought.
The image is indeed not cached by my addon, instead only the Bing response that holds the link for the image is cached.
So when you open new tab page, the image will be indeed "downloaded" from their servers.
However, the image response comes with `"cache-control: public, max-age=691200"` (in seconds) which is 8 days. So your browser should not reload it every time you open new tab but instead it should load it from the cache for those 8 days.
![image](https://user-images.githubusercontent.com/55486931/212473499-1a7576c0-e1b5-4530-b7a1-1a5ba2098398.png)

Like this:
![image](https://user-images.githubusercontent.com/55486931/212473551-df293586-9e72-46d8-aaca-435a68eea904.png)

Did you somehow disabled browser cache?

**Comment by simurq** [comment] 2023-01-18 17:14
Juraj, thank you very much for trying to help!!!

You were right regarding the disabled browser cache - I've checked these two variables in my browser (Firefox 108): `browser.cache.disk.enable` was set to `false`, but `browser.cache.memory.enable` was untouched and set to `true`, as it should be.

Nevertheless, it didn't help to solve the issue for me. :o( Tabs still reload images from unsplash during the same browser session. This is the [unsplash link](https://source.unsplash.com/random?orientation=landscape&size=1920x1080) I use. But Bing image of the day remains the same, which is a good sign - I mean it doesn't update on each new tab.

Is there any other setting I need to change to enable the browser cache except the above duo?

Thanks!

**Comment by fastaddons** [comment] 2023-02-20 14:50
Hello,
I'm sorry it's taking me so long to reply :(
I can't really tell which "about:config" values to change, it's best to not touch anything in there because you can easily break things.

**Regarding the "Unsplash link", that's a pretty cool link!**
But since the fetch happens when the page loads, it will return new image with a delay every time the dials page loads.
So to make this work properly, I would have to integrate it similarly to the Bing service. 
**And I think I will, since this is really cool! Thank for letting me know!**
I'll see what I can do, maybe even in the next release.

**Comment by fastaddons** [comment] 2023-02-21 16:04
I've added a caching for the URL images.
So if you set URL as background, it's gonna download it and cache it for 8 hours.
It should work automatically, in the upcoming version 22.3.

**Closed by fastaddons** 2023-02-21 16:04 UTC
Labels: enhancement

**Comment by simurq** [comment] 2023-03-22 07:10
Good morning, Juraj!

Just wanted to say THANK YOU for all you do for this small community of GSD fans, particularly for what you did with caching the custom background images in the app! 👍🏼 It now works as expected.

Have a nice day and please keep it up!

**Comment by fastaddons** [comment] 2023-03-22 13:58
I'm happy it worked :), have a nice day too!
