### ISSUE TITLE
Stop the internet connectivity and the ADDIN will go crazy ... CPU over 50% costantly

### ISSUE THREAD

**Issue by pulsar14** [fastaddons/GroupSpeedDial#147] opened 2022-06-18 22:05 UTC
**Describe the bug**
Addin in loop trying to sync to the cloud after some minutes the internet goes down
 
**Steps To Reproduce**
1) Stop the internet connectivity
2) GroupSpeedDial next schedule, try to sync and sync and sync to the cloud obviously without success ... but the addin continue to loop trying to sync .... and it starts to suck CPU cycles and heat the machine with no sense. Browser keeps CPU over 50%

**Expected behavior**
No internet ... no sync ... no activity ... no suck of energy and resources (huge energy impact!)

**Device info:**
 - operating system: Win 10 pro x64
 - Browser and version: Firefox (always last release)
 - GroupSpeedDial version: I don't know ... in the About there's no version

**Additional info**
Add any other info about the problem here.
Open "about:performance" and You can see what happen after a while when you close your internet ...

**Comment by fastaddons** [comment] 2022-06-19 07:24
Hello,
How can you tell it's my addon causing the CPU stress?
Visit the `about:processes` page, that should tell you which process / addon is taking the CPU. 

But I really doubt it's my addon, because in case the internet is not available, it will retry with 2x delay period with each failed response, so it will retry after 2 seconds, 4, 8, 16, 32, 64 seconds and so on.

**Comment by pulsar14** [comment] 2022-06-20 18:03
Thank U for the response, Please take a look at this short video so You can see what I’m speaking about.Regards WITH INTERNET AVAILABLE:   WITHOUT INTERNET (almost 15 min later): Please, see the Video in attachment      From: Juraj MäsiarSent: Sunday, June 19, 2022 9:24 AMTo: fastaddons/GroupSpeedDialCc: Stefano.Scalcinati; AuthorSubject: Re: [fastaddons/GroupSpeedDial] Stop the internet connectivity and the ADDIN will go crazy ... CPU over 50% costantly (Issue #147) Hello,How can you tell it's my addon causing the CPU stress?Visit the about:processes page, that should tell you which process / addon is taking the CPU.But I really doubt it's my addon, because in case the internet is not available, it will retry with 2x delay period with each failed response, so it will retry after 2 seconds, 4, 8, 16, 32, 64 seconds and so on.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by fastaddons** [comment] 2022-06-22 21:13
Thanks for the video!
Could you open:
```
about:devtools-toolbox?id=admin%40fastaddons.com_GroupSpeedDial&type=extension
```
And switch to "Network" tab and send me a screenshot or video of the requests you see there.

I will be releasing new version 21.0 in a few days which will use upgraded synchronization (compatible with upcoming Manifest V3) so it may fix it, but let's be sure, I really want to know that requests fails. Thanks!

**Comment by fastaddons** [comment] 2022-06-22 21:29
OK never mind, I can reproduce it now!
My whole Firefox froze.
I will investigate and this will be 100% fixed in the upcoming release.
Thank you for reporting this!

**Comment by fastaddons** [comment] 2022-06-27 11:43
So, this was an interesting bug to fix. 
It turns out, my plan with multiplying the delay period backfired because each opening/reloading of dials page would generate a new request which would schedule next reload with 2x delay, but after several reloads the value would exponentially grow and overflow into something that browser would interpret as zero, which then caused immediate execution. Crazy!

In any case, I've fixed it now so that it won't go below 9 seconds and above 10 minutes.
The new version 21.0 should be released this week unless I find more issues.

Thank you again for reporting this! I will close this bug once it's released.

**Comment by pulsar14** [comment] 2022-06-27 14:18
Sorry for my late response, happy that You find a solution. **Great work!**

**Closed** 2022-07-06 08:53 UTC
Labels: bug
