### ISSUE TITLE
Environment health-check error: Error

### ISSUE THREAD

**Issue by JerryLutor** [fastaddons/GroupSpeedDial#16] opened 2020-08-30 05:45 UTC
**Describe the bug**

After updating the mozilla to the 80th version, the plugin began to fall. Reinstallation does not work.

Environment health-check error: Error
Could not establish connection. Receiving end does not exist.
o@moz-extension://cfc2e7d1-0c01-493c-80b0-207fb9314f06/dial.js:1:23359

Error: Could not establish connection. Receiving end does not exist.

**Steps To Reproduce**
A minute later, the plugin may stop loading in a new tab.

**Expected behavior**

Environment health-check error: Error
Could not establish connection. Receiving end does not exist.

**Device info:**
 - operating system: Windows 10 x64
 - Browser and version: mozilla 80.0 x64
 - GroupSpeedDial version:  14.9

**Additional info**

**Comment by Juraj-Masiar** [comment] 2020-08-30 06:48
Hello,
Thanks for reporting. I've received many emails since Firefox 80 was released.
Tell me, after it happens, does your other extensions works? Try to click on each one in the toolbar to see if their popup windows works fine.

It's most probably this bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1655916
So far restarting Firefox is the easiest fix, but may not permanent.
I'm still waiting for Firefox team to respond there.

The problem seems to be that operating system kills the webextensions process (or it crashes).

**Comment by JerryLutor** [comment] 2020-08-30 08:30
Problem on all addons

**Comment by JerryLutor** [comment] 2020-09-03 18:25
An update to the plugin's mozilla brought results. Plugins began to crash not immediately, but after a few minutes.

**Comment by schmurtzm** [comment] 2020-09-07 13:58
Same here, a lot of crash with firefox 80

Agree to say that once the problem appear other add-ons don't have popups anymore but however it seems that this behavior is triggered by GroupSpeedDial (because no more problems on other add-ons after disabling GroupSpeedDial).

May be a workaround : desactivate GroupSpeedDial add-on and reactivate it, open a new tab and you should see a popup at the top right "Your new tab has changed" , click "Keep changes" and pry.

**Comment by fastaddons** [comment] 2020-09-07 14:11
I don't think this is related to my addon. There are people reporting same behavior also on reddit:
https://www.reddit.com/r/firefox/comments/ilil8t/addons_stopped_working/

The fact that you can see your dials page as crashed tab is because it's the only addon page you have opened :), I'm sure if you had another one opened it would crash as well.

I was experiencing it on Firefox 80 as well (maybe 4 times), but then 81 was released and I haven't seen it anymore.
So there is chance they changed something and it's already fixed in 81.

But the 81 is still beta, so DON'T upgrade to Beta because there is no downgrade path and you would have to stay on Beta.
Firefox 81 will be released in two weeks and one day, so just be patient :).

Until then, just restart Firefox when the bug occurs and it should fix the problem.

**Comment by schmurtzm** [comment] 2020-09-10 19:54
> I don't think this is related to my addon. There are people reporting same behavior also on reddit:
> https://www.reddit.com/r/firefox/comments/ilil8t/addons_stopped_working/

After many hours of test I can confirm that GroupSpeedDial trigger the bug. I understand that the bug comes from firefox but when I deactivate GroupSpeedDial it never happens again in my case. So I deactivate GroupSpeedDial with regrets, looking forward FF 81.0 to re-activate it  :wink:

**Comment by fastaddons** [comment] 2020-09-10 21:13
I guess it could be related to higher memory usage in my addon compared to some smaller addons (not many addons needs to handle many high resolution images). 

**Do you have auto-reload enabled for some of your dials?**
**Or can you see some pattern that would help reproducing the problem?**

Also, if you have cloud account, you can use the Cloud Dials page - it's a web version of the dials page and if you enable thumbnails synchronization it will look exactly the same. And it can be used in any browser. But it's not editable though...

**Comment by JerryLutor** [comment] 2020-09-15 05:44
Page preloading is enabled (5 minutes interval). But the falls are chaotic. There is no longer so much a problem in adon as in the fact that something has changed since version 80. All plugins fall.

**Comment by Juraj-Masiar** [comment] 2020-09-15 07:05
Hi @JerryLutor , could you try to disable auto-reload? (maybe for a few days?)
From Options page / Thumbnails / Auto reload - "Disable on this device" checkbox.

Thumbnails generation can consume a lot of memory and Firefox is sometimes releasing it only slowly.
As this problem may be related to memory consumption, this could help with the problem.

Also the Firefox 81 will be released 7 days from now and there is good chance it fixes the problem.

**Comment by JerryLutor** [comment] 2020-09-15 15:05
I turned off auto-update thumbnails and a miracle happened. all add-ons stopped falling. now I turn it on again and I will watch.

**Comment by fastaddons** [comment] 2020-09-29 06:59
Seems like this was indeed fixed by Firefox 81. If you are still experiencing this issue even in 81, please let me know.

**Closed by fastaddons** 2020-09-29 06:59 UTC
Labels: bug
