### ISSUE TITLE
Auto-generated thumbnail does not auto-reload (revisited)

### ISSUE THREAD

**Issue by TigBuh99** [fastaddons/GroupSpeedDial#157] opened 2022-08-18 04:58 UTC
I opened a bug report in June, now closed in [(https://github.com/fastaddons/GroupSpeedDial/issues/143)]

The problem lately is that the refreshed thumbnail leaves the respective tab open. This probably happens mostly when I'm away from the computer.

The tab used to refresh the thumbnail should not remain open.

**Device info:**
 - operating system: Windows 11 Pro
 - Browser and version: Chrome Version 104.0.5112.81 (Official Build) (64-bit)
 - GroupSpeedDial version: 21.4

I attach an image showing the tabs after the PC was left on all night.
![thumbnail-tabs](https://user-images.githubusercontent.com/49759462/185297220-2320be88-187c-4821-9bf1-6ca0b5b88ccb.png)

**Comment by fastaddons** [comment] 2022-08-18 06:56
Hello,
Thanks for reporting.
I've noticed this last week, I'm not sure why but it seems to be opening on browser start, or something like that...
I will fix this in the next release. It would be fixed already but I've got sick so I've been home getting rest.

**Comment by TigBuh99** [comment] 2022-08-18 07:39
> Hello, Thanks for reporting. I've noticed this last week, I'm not sure why but it seems to be opening on browser start, or something like that... I will fix this in the next release. It would be fixed already but I've got sick so I've been home getting rest.

Just get well soon. It's not a significant problem, just an annoyance.

**Comment by fastaddons** [comment] 2022-08-18 19:28
So I've been looking at this now and the tabs indeed appears after restart. So if reload a lot of dials, they will reappear after restart!

Sadly, this is a Chromium bug. The good news is, it seems to be fixed in Chromium 105, which will be released in 12 days (not so great).

I've reported it here;
https://bugs.chromium.org/p/chromium/issues/detail?id=1354282

I'll see if I can somehow fix it on my end before them.

**Comment by fastaddons** [comment] 2022-09-01 07:00
Hello, so my Chrome updated today to 105 but the bug is still present. 
Yet in my Chrome Beta, which is still105, the bug is not present. I hate when things doesn't make sense...

So it looks like I'm gonna have to fix it somehow myself after all :(.

**Comment by fastaddons** [comment] 2022-09-19 08:59
I've released new version 21.6 that fixes this problem.

**Closed by fastaddons** 2022-09-19 08:59 UTC
Labels: bug

**Comment by TigBuh99** [comment] 2022-10-01 11:12
We are on Chrome v.106 and Group Speed Dial v.21.8, but sadly the problem described above remains unsolved. Refreshed dials create a series of tabs that should not be there in the first place.

**Comment by fastaddons** [comment] 2022-10-01 14:22
The bug in Chrome was not fixed but I've released fix in 21.6 that should help. I've tested it in 106 and it works.
Can you send me some steps to reproduce it?
Before I could simply reload any dial and after restarting Chrome that page would be opened as pinned.

**Comment by TigBuh99** [comment] 2022-10-02 05:42
The dial that I reload is https://www.bbc.co.uk/news/uk and the refresh time is set at 15 minutes. Most usual is that I leave my PC open at night and Chrome is open as well. In the morning I see a number of tabs of the above website on the left side of the monitor. I don't see this much during daytime, perhaps because I use Chrome on and off all day.

Are you suggesting that I should revert to v.21.6?

**Comment by fastaddons** [comment] 2022-10-03 08:14
Interesting... so this is a different bug.
Just to clarify:
1. your PC is running whole night?
1. it won't go to sleep automatically?
1. And in the morning the Chrome is still running, you are not opening Chrome, right?
1. in the "Auto-reload" tab, which "Refresh method" are you using? Is it set to "Default"?

**Comment by TigBuh99** [comment] 2022-10-03 10:49
My PC is running the whole night and it doesn't go to sleep. The setting for going to sleep is "never". The screen however switches off after 15 minutes of inactivity.
Chrome is open and running all night, I only switch to its window to access and use it.
The "Auto-reload" tab setting is set to "Default".

**Comment by fastaddons** [comment] 2022-10-03 16:13
When you see pinned tabs next time, open the dials page, then go to the main menu (upper right corner) and select Advanced / Send error logs. Then send me those logs (or paste it here).

From what I can think of, if the reloading process is really slow, the background script (a service worker) could get killed and then the tab would stay opened. But the reloading should only take a few seconds so that's unlikely... unless Chrome can detect disabled monitor. But it's possible... we should see that in the logs.

**Comment by TigBuh99** [comment] 2022-10-05 06:18
There was only one pinned tab last night and here's the log.

`Environment: Group Speed Dial 21.8; name: chrome, version: 106; arch: x86-64, nacl_arch: x86-64, os: win;
API check: storage.session: true, OffscreenCanvas: true
Pixel ratio: 1
Running time: 0.03s
Stats: NA - 18,3,5,9,3,13,10,5
{"indexedDB":"3.4MB","storageLocal":"19.4KB","storageSync":"11.4KB","localStorage":"3.8KB"}
Runtime logs:
2022-10-05T02:58:25.619Z -11652383ms, bc - isAndroidPromise
2022-10-05T02:58:25.620Z     1ms, bc - store
2022-10-05T02:58:25.620Z     0ms, bc - OPTIONS_PROMISE
2022-10-05T03:07:05.507Z 519887ms, bc - logger service started
2022-10-05T03:07:05.520Z    13ms, bc - isAndroidPromise
2022-10-05T03:07:05.522Z     2ms, bc - store
2022-10-05T03:07:05.522Z     0ms, bc - OPTIONS_PROMISE
2022-10-05T03:07:17.125Z 11603ms, fr - iframe timeout
undefined
Error
    at d (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.js:1:62494)
    at n (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.js:1:96259)
    at T (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.js:1:81850)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.js:1:65522
2022-10-05T03:07:36.791Z 19666ms, bc - takeScreenShot 
window was not visible!
{"active":true,"audible":false,"autoDiscardable":false,"discarded":false,"favIconUrl":"data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7","groupId":-1,"height":892,"highlighted":true,"id":1919292661,"incognito":false,"index":0,"mutedInfo":{"extensionId":"imfeikbeimbfpmgfkkmjekabdehiiajc","muted":true,"reason":"extension"},"pinned":false,"selected":true,"status":"loading","title":"______________________________________________","url":"chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.html","width":1822,"windowId":1919292664}
Error
    at h (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:157101)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:157389
    at async chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:44729
2022-10-05T03:07:36.795Z     4ms, bc - reloading failed, unexpected error
Error
An unexpected error occurred
Error: An unexpected error occurred
{"groupId":0,"url":"https://www.bbc.co.uk/news/uk","type":0,"isManualReload":false,"isVisibleSpin":false,"refreshMethod":1,"value":900,"isGroupDial":false,"lastRunTime":1664938325159,"nextRunTime":1664939225159}
Error
    at h (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:157101)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:70273
    at async bt (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:70208)
    at async Promise.all (index 0)
    at async Object.callback (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:69206)
    at async chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:69476
2022-10-05T03:22:48.828Z 912033ms, bc - logger service started
2022-10-05T03:22:48.836Z     8ms, bc - isAndroidPromise
2022-10-05T03:22:48.837Z     1ms, bc - store
2022-10-05T03:22:48.838Z     1ms, bc - OPTIONS_PROMISE
2022-10-05T03:23:00.126Z 11288ms, fr - iframe timeout
undefined
Error
    at d (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.js:1:62494)
    at n (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.js:1:96259)
    at T (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.js:1:81850)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.js:1:65522
2022-10-05T03:23:19.807Z 19681ms, bc - takeScreenShot 
window was not visible!
{"active":true,"audible":false,"autoDiscardable":false,"discarded":false,"favIconUrl":"data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7","groupId":-1,"height":892,"highlighted":true,"id":1919292667,"incognito":false,"index":0,"mutedInfo":{"extensionId":"imfeikbeimbfpmgfkkmjekabdehiiajc","muted":true,"reason":"extension"},"pinned":false,"selected":true,"status":"loading","title":"______________________________________________","url":"chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.html","width":1822,"windowId":1919292670}
Error
    at h (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:157101)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:157389
    at async chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:44729
2022-10-05T03:23:19.810Z     3ms, bc - reloading failed, unexpected error
Error
An unexpected error occurred
Error: An unexpected error occurred
{"groupId":0,"url":"https://www.bbc.co.uk/news/uk","type":0,"isManualReload":false,"isVisibleSpin":false,"refreshMethod":1,"value":900,"isGroupDial":false,"lastRunTime":1664939256840,"nextRunTime":1664940156840}
Error
    at h (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:157101)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:70273
    at async bt (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:70208)
    at async Promise.all (index 0)
    at async Object.callback (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:69206)
    at async chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:69476
2022-10-05T03:38:20.030Z 900220ms, bc - logger service started
2022-10-05T03:38:20.039Z     9ms, bc - isAndroidPromise
2022-10-05T03:38:20.040Z     1ms, bc - store
2022-10-05T03:38:20.041Z     1ms, bc - OPTIONS_PROMISE
2022-10-05T03:38:32.132Z 12091ms, fr - iframe timeout
undefined
Error
    at d (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.js:1:62494)
    at n (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.js:1:96259)
    at T (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.js:1:81850)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.js:1:65522
2022-10-05T03:38:51.817Z 19685ms, bc - takeScreenShot 
window was not visible!
{"active":true,"audible":false,"autoDiscardable":false,"discarded":false,"favIconUrl":"data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7","groupId":-1,"height":892,"highlighted":true,"id":1919292673,"incognito":false,"index":0,"mutedInfo":{"extensionId":"imfeikbeimbfpmgfkkmjekabdehiiajc","muted":true,"reason":"extension"},"pinned":false,"selected":true,"status":"loading","title":"______________________________________________","url":"chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.html","width":1822,"windowId":1919292676}
Error
    at h (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:157101)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:157389
    at async chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:44729
2022-10-05T03:38:51.821Z     4ms, bc - reloading failed, unexpected error
Error
An unexpected error occurred
Error: An unexpected error occurred
{"groupId":0,"url":"https://www.bbc.co.uk/news/uk","type":0,"isManualReload":false,"isVisibleSpin":false,"refreshMethod":1,"value":900,"isGroupDial":false,"lastRunTime":1664940199857,"nextRunTime":1664941099857}
Error
    at h (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:157101)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:70273
    at async bt (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:70208)
    at async Promise.all (index 0)
    at async Object.callback (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:69206)
    at async chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:69476
2022-10-05T03:53:52.034Z 900213ms, bc - logger service started
2022-10-05T03:53:52.042Z     8ms, bc - isAndroidPromise
2022-10-05T03:53:52.043Z     1ms, bc - store
2022-10-05T03:53:52.044Z     1ms, bc - OPTIONS_PROMISE
2022-10-05T03:54:04.121Z 12077ms, fr - iframe timeout
undefined
Error
    at d (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.js:1:62494)
    at n (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.js:1:96259)
    at T (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.js:1:81850)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.js:1:65522
2022-10-05T03:54:23.800Z 19679ms, bc - takeScreenShot 
window was not visible!
{"active":true,"audible":false,"autoDiscardable":false,"discarded":false,"favIconUrl":"data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7","groupId":-1,"height":892,"highlighted":true,"id":1919292679,"incognito":false,"index":0,"mutedInfo":{"extensionId":"imfeikbeimbfpmgfkkmjekabdehiiajc","muted":true,"reason":"extension"},"pinned":false,"selected":true,"status":"loading","title":"______________________________________________","url":"chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.html","width":1822,"windowId":1919292682}
Error
    at h (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:157101)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:157389
    at async chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:44729
2022-10-05T03:54:23.803Z     3ms, bc - reloading failed, unexpected error
Error
An unexpected error occurred
Error: An unexpected error occurred
{"groupId":0,"url":"https://www.bbc.co.uk/news/uk","type":0,"isManualReload":false,"isVisibleSpin":false,"refreshMethod":1,"value":900,"isGroupDial":false,"lastRunTime":1664941131866,"nextRunTime":1664942031866}
Error
    at h (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:157101)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:70273
    at async bt (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:70208)
    at async Promise.all (index 0)
    at async Object.callback (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:69206)
    at async chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:69476
2022-10-05T04:09:24.011Z 900208ms, bc - logger service started
2022-10-05T04:09:24.022Z    11ms, bc - isAndroidPromise
2022-10-05T04:09:24.024Z     2ms, bc - store
2022-10-05T04:09:24.024Z     0ms, bc - OPTIONS_PROMISE
2022-10-05T04:09:36.120Z 12096ms, fr - iframe timeout
undefined
Error
    at d (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.js:1:62494)
    at n (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.js:1:96259)
    at T (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.js:1:81850)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.js:1:65522
2022-10-05T04:09:55.832Z 19712ms, bc - takeScreenShot 
window was not visible!
{"active":true,"audible":false,"autoDiscardable":false,"discarded":false,"favIconUrl":"data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7","groupId":-1,"height":892,"highlighted":true,"id":1919292685,"incognito":false,"index":0,"mutedInfo":{"extensionId":"imfeikbeimbfpmgfkkmjekabdehiiajc","muted":true,"reason":"extension"},"pinned":false,"selected":true,"status":"loading","title":"______________________________________________","url":"chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.html","width":1822,"windowId":1919292688}
Error
    at h (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:157101)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:157389
    at async chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:44729
2022-10-05T04:09:55.837Z     5ms, bc - reloading failed, unexpected error
Error
An unexpected error occurred
Error: An unexpected error occurred
{"groupId":0,"url":"https://www.bbc.co.uk/news/uk","type":0,"isManualReload":false,"isVisibleSpin":false,"refreshMethod":1,"value":900,"isGroupDial":false,"lastRunTime":1664942063845,"nextRunTime":1664942963845}
Error
    at h (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:157101)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:70273
    at async bt (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:70208)
    at async Promise.all (index 0)
    at async Object.callback (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:69206)
    at async chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:69476
2022-10-05T04:25:56.052Z 960215ms, bc - logger service started
2022-10-05T04:25:56.061Z     9ms, bc - isAndroidPromise
2022-10-05T04:25:56.062Z     1ms, bc - store
2022-10-05T04:25:56.063Z     1ms, bc - OPTIONS_PROMISE
2022-10-05T04:26:08.122Z 12059ms, fr - iframe timeout
undefined
Error
    at d (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.js:1:62494)
    at n (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.js:1:96259)
    at T (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.js:1:81850)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.js:1:65522
2022-10-05T04:26:27.803Z 19681ms, bc - takeScreenShot 
window was not visible!
{"active":true,"audible":false,"autoDiscardable":false,"discarded":false,"favIconUrl":"data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7","groupId":-1,"height":892,"highlighted":true,"id":1919292691,"incognito":false,"index":0,"mutedInfo":{"extensionId":"imfeikbeimbfpmgfkkmjekabdehiiajc","muted":true,"reason":"extension"},"pinned":false,"selected":true,"status":"loading","title":"______________________________________________","url":"chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/reload/reload.html","width":1822,"windowId":1919292694}
Error
    at h (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:157101)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:157389
    at async chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:44729
2022-10-05T04:26:27.808Z     5ms, bc - reloading failed, unexpected error
Error
An unexpected error occurred
Error: An unexpected error occurred
{"groupId":0,"url":"https://www.bbc.co.uk/news/uk","type":0,"isManualReload":false,"isVisibleSpin":false,"refreshMethod":1,"value":900,"isGroupDial":false,"lastRunTime":1664942995885,"nextRunTime":1664943895885}
Error
    at h (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:157101)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:70273
    at async bt (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:70208)
    at async Promise.all (index 0)
    at async Object.callback (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:69206)
    at async chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background_gsd.worker.js:2:69476
2022-10-05T06:12:38.002Z 6370194ms, bc - logger service started
2022-10-05T06:12:38.019Z    17ms, bc - isAndroidPromise
2022-10-05T06:12:38.021Z     2ms, bc - store
2022-10-05T06:12:38.022Z     1ms, bc - OPTIONS_PROMISE
2022-10-05T06:13:17.302Z 39280ms, bc - First tab starts loading.
`

**Comment by fastaddons** [comment] 2022-10-05 08:37
Thanks!
Now it makes sense.
The error "takeScreenShot window was not visible" means that Chrome window was outside of monitor, this means that monitor is disconnected when it goes to sleep.
Additionally, even there is error "iframe timeout", so the page won't load at all if there is no monitor. That's why the backup refresh in pinned tab is used.
And I would guess that also fails with timeout which is set to similar value as the time to takes to kill the service worker that orchestrating all this. So if Chrome kills it before the timeout, it will keep the pinned tab opened.

I'm not sure how to fix it yet, but I'll think of something and release it soon in the upcoming 21.9 version.

**Comment by TigBuh99** [comment] 2022-10-05 18:13
Thank you for looking at this matter. I'll leave Firefox open all night, to see if the same problem occurs with it.

**Comment by fastaddons** [comment] 2022-10-05 20:02
It can't happen in Firefox because Firefox doesn't use pinned tabs at all. 
Also, it doesn't use service workers so the background script can't be killed. That way even if the reload fails, it will always be closed.

**Comment by TigBuh99** [comment] 2022-10-06 18:19
Thank you for the information about Firefox. It shows how little I know!
